<div class="ui vertical masthead segment">
    <div class="ui container">
        <div class="ui secondary inverted pointing menu">
            <a class="toc item">
                <i class="sidebar icon"></i>
            </a>
            <div class="header item">
                <h4 class="ui inverted header">
                    <img src="<?php echo $this->baseUrl('public/modules/default/img/brand/logotipo_inverted.svg') ?>" />
                    <div class="content">
                            Weone
                        <div class="sub header">Consultoria Digital</div>
                    </div>
                </h4>
            </div>
            <div class="right item">
                <div class="item">
                    <a class="ui button" href="<?php echo $this->baseUrl('account/sign/in') ?>">Painel de controle</a>
                </div>
            </div>
        </div>
    </div>

    <div class="ui center aligned text container">
        <h1 class="ui inverted header">
            Site em construção
        </h1>
        <h3 class="ui inverted header">Aguarde... Estamos criando uma nova experiência digital para você!</h3>
    </div>
</div>
