<style type="text/css">
    body {
        background-color: #DADADA;
    }
    
    h2.ui.center.aligned.blue.header {
        margin-top: 20px;
    }
</style>
<div class="ui equal width centered grid container">
    <div class="six wide column">
        <h2 class="ui center aligned blue header">
            ENTRE COM SUA CONTA
        </h2>
        <form class="ui large form stacked segment">
            <div class="field">
                <label>Seu e-mail</label>
                <div class="ui left icon input">
                    <i class="user icon"></i>
                    <input type="text" name="mail" placeholder="Seu e-mail">
                </div>
            </div>
            <div class="field">
                <label>Sua senha</label>
                <div class="ui left icon input">
                    <i class="lock icon"></i>
                    <input type="password" name="password" placeholder="Sua senha">
                </div>
            </div>
            <div class="ui error message"></div>
            <button class="ui blue right labeled icon button"><i class="right arrow icon"></i> Entrar</button>
        </form>
    </div>
</div>