<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-BR">
    <head>  
        <?php
        echo $this->headTitle("Site " . $this->title);

        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')
                ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('language', 'pt-BR')
                ->appendHttpEquiv('Author', 'Department web')
                ->appendHttpEquiv('reply-to', 'suporte@weone.com.br')
                ->appendName('robots', 'noindex, nofollow')
                ->appendName('title', 'title')
                ->appendName('description', 'description');

        echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->baseUrl('public/modules/default/img/favicon/favicon.ico'), 'type' => 'image/x-icon'), 'PREPEND')
                ->prependStylesheet($this->baseUrl('public/framework/semantic.min.css'));
        ?>        
    </head>
    <body>
        
        <?php echo $this->layout()->content; ?>

        <footer>
            <div class="ui very padded vertical basic segment">
                <div class="ui equal width grid container">
                    <div class="column">
                        <h6 class="ui center aligned header">
                            VOLTAR PARA <a href="<?php echo $this->baseUrl('/') ?>">PÁGINA INCIAL</a>
                            <br />
                            <?php echo date('Y') ?> © TODOS OS DIREITOS RESERVADOS.
                        </h6>
                    </div>
                </div>
            </div> 
        </footer>
        
        <?php
        echo $this->headScript()
                ->prependFile($this->baseUrl('public/config/base_url.js'))
                ->prependFile($this->baseUrl('public/framework/semantic.min.js'))
                ->prependFile($this->baseUrl('public/library/jquery/jquery.js'));
        ?>

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-77935163-2', 'auto');
            ga('send', 'pageview');
        </script>

    </body>
</html>