<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-BR">
    <head>  
        <?php
        echo $this->headTitle("Agenda Online");

        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')
                ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('language', 'pt-BR')
                ->appendHttpEquiv('Author', 'Department web')
                ->appendHttpEquiv('reply-to', 'suporte@weone.com.br')
                ->appendName('robots', 'index, follow');

        echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->baseUrl('public/modules/default/img/favicon/favicon.ico'), 'type' => 'image/x-icon'), 'PREPEND')
                ->prependStylesheet($this->baseUrl('public/library/introjs/intro.css'))
                ->prependStylesheet($this->baseUrl('public/framework/semantic.min.css'));
        ?>
    </head>
    <body>

        <div class="ui text menu">
            <div class="ui container">
                <div class="header item">
                    <h5 class="ui green header">
                        Agenda Online
                        <div class="sub header">Sistema de agendamento</div>
                    </h5>
                </div>

                <div class="right menu">
                    <div class="item"><button class="ui icon basic button"><i class="mail outline icon"></i></button></div>
                    <div class="item"><img class="ui right spaced avatar image" src="http://semantic-ui.com/images/avatar/small/elliot.jpg" /></div>
                    <div class="item">
                        <h5 class="ui header">
                            <?php echo Zend_Auth::getInstance()->getIdentity()->firstname ?> <?php echo Zend_Auth::getInstance()->getIdentity()->lastname ?>
                            <div class="sub header"><a href="<?php echo $this->baseUrl('account/sign/out') ?>">Encerrar sessão</a></div>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="ui divider"></div>

        <?php echo $this->layout()->content; ?>

        <?php
        echo $this->headScript()
                ->prependFile($this->baseUrl('public/library/introjs/intro.js'))
                ->prependFile($this->baseUrl('public/framework/semantic.js'))
                ->prependFile($this->baseUrl('public/config/base_url.js'))
                ->prependFile($this->baseUrl('public/library/jquery/jquery.js'));
        ?>

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-77935163-2', 'auto');
            ga('send', 'pageview');
        </script>

    </body>
</html>