<?php echo $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-BR">
    <head>  
        <?php
        echo $this->headTitle('...');

        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')
                ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('language', 'pt-BR')
                ->appendHttpEquiv('Author', '...')
                ->appendHttpEquiv('reply-to', '...')
                ->appendHttpEquiv('expires', '-1')
                ->appendHttpEquiv('pragma', 'no-cache')
                ->appendHttpEquiv('Cache-Control', 'no-cache')
                ->appendName('robots', 'noindex, nofollow')
                ->appendName('DC.title', '...')
                ->appendName('description', '...');

        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => ""), 'PREPEND')
                ->appendStylesheet($this->baseUrl('/public/framework/css/uikit.css'));        
        ?>

    </head>
    <body>

        <?php echo $this->layout()->content; ?>

        <?php
        echo $this->headScript()
                ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js');                        
        ?>

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-63554195-1', 'auto');
            ga('send', 'pageview');
        </script>
    </body>
</html>