<section>
    <div class="ui very padded basic segment">
        <div class="ui equal width stackable grid container">
            <div class="row">
                <div class="four wide column">
                    <div class="ui segment">
                        <div class="ui vertical fluid menu">
                            <a class="item" href="<?php echo $this->baseUrl('dashboard/event') ?>">Plantões</a>
                            <a class="item" href="<?php echo $this->baseUrl('dashboard/user') ?>">Dizimistas</a>
                            <a class="item" href="<?php echo $this->baseUrl('dashboard/oncall') ?>">Plantonistas</a>
                            <a class="item" href="<?php echo $this->baseUrl('dashboard/report') ?>">Relatórios</a>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="ui segment">
                        <table class="ui table">
                            <thead>
                                <tr>
                                    <th>DATA E HORA</th>
                                    <th>SITUAÇÃO</th>
                                    <th>OPÇÕES</th>
                                </tr>                                
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>