<section>
    <div class="uk-container uk-container-center">
        <div class="uk-grid uk-margin-large-top uk-margin-large-bottom">
            <div class="uk-width-1-1">
                <h1 class="uk-text-center"><?php echo $this->message ?></h1>
                <p class="uk-text-center"><b>Mensagem:</b> <?php echo $this->exception->getMessage() ?></p>
            </div>
        </div>
    </div>
</section>
